IMPORT LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
cl_df = pd.read_csv('calories.csv')
cl_df.head(2)

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0

In [4]:
ex_df = pd.read_csv('exercise.csv')
ex_df.head(2)

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3

In [9]:
ex_df = ex_df.merge(cl_df, on= 'User_ID')

In [10]:
ex_df.head()

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0

In [11]:
ex_df.shape

(15000, 9)

In [12]:
ex_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_ID     15000 non-null  int64
 1   Gender      15000 non-null  object
 2   Age         15000 non-null  int64
 3   Height      15000 non-null  float64
 4   Weight      15000 non-null  float64
 5   Duration    15000 non-null  float64
 6   Heart_Rate  15000 non-null  float64
 7   Body_Temp   15000 non-null  float64
 8   Calories    15000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 1.0+ MB

In [13]:
ex_df.isnull().sum()

User_ID       0
Gender        0
Age           0
Height        0
Weight        0
Duration      0
Heart_Rate    0
Body_Temp     0
Calories      0
dtype: int64

In [14]:
ex_df.describe()

,User_ID,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
count,1.500000e+04,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,1.497736e+07,42.789800,174.465133,74.966867,15.530600,95.518533,40.025453,89.539533
std,2.872851e+06,16.980264,14.258114,15.035657,8.319203,9.583328,0.779230,62.456978
min,1.000116e+07,20.000000,123.000000,36.000000,1.000000,67.000000,37.100000,1.000000
25%,1.247419e+07,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,35.000000
50%,1.499728e+07,39.000000,175.000000,74.000000,16.000000,96.000000,40.200000,79.000000
75%,1.744928e+07,56.000000,185.000000,87.000000,23.000000,103.000000,40.600000,138.000000
max,1.999965e+07,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000

In [15]:
ex_df['Gender'].value_counts()

Gender
female    7553
male      7447
Name: count, dtype: int64

In [20]:
ex_df['Gender'] = ex_df['Gender'].map({'female':0, 'male':1})

In [21]:
ex_df.head(2)

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,1,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,0,20,166.0,60.0,14.0,94.0,40.3,66.0

TRAIN TEST SPLIT

In [80]:
ex_df_new = ex_df.drop('Calories', axis = 1)

In [81]:
X= ex_df_new.drop('User_ID', axis = 1)

In [82]:
X.head(3)

   Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0       1   68   190.0    94.0      29.0       105.0       40.8
1       0   20   166.0    60.0      14.0        94.0       40.3
2       1   69   179.0    79.0       5.0        88.0       38.7

In [83]:
X.shape

(15000, 7)

In [84]:
y = ex_df['Calories']

In [85]:
y.shape

(15000,)

In [86]:
from sklearn.model_selection import train_test_split

In [87]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [88]:
X_train.shape

(12000, 7)

In [89]:
X_test.shape

(3000, 7)

In [90]:
y_train.shape

(12000,)

In [91]:
y_test.shape

(3000,)

MODEL SELECTION

In [92]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [93]:
rfr= RandomForestRegressor()
rfr.fit(X_train, y_train)
y_pred= rfr.predict(X_test)
score = r2_score(y_test, y_pred)
score

0.9981936311358971

In [94]:
models ={'lr':LinearRegression(), 'logr': LogisticRegression(), 'dtr': DecisionTreeRegressor(), 'rfr': RandomForestRegressor(), 'ridge':Ridge(), 'lasso': Lasso()}
result={}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred= model.predict(X_test)
    score = r2_score(y_test, y_pred)
    # result[name]= score
    print(f"{name}: MSE: {mean_squared_error(y_test, y_pred)} Score:{score}")

lr: MSE: 131.99574575081698 Score:0.9672937151257295

C:\Users\MONISALI\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

logr: MSE: 1258.3386666666668 Score:0.6882052321746516
dtr: MSE: 27.138333333333332 Score:0.9932755858458611
rfr: MSE: 7.391314166666667 Score:0.9981685589535091
ridge: MSE: 131.99625903139344 Score:0.9672935879435945
lasso: MSE: 143.82689461175065 Score:0.9643621590908397

In [96]:
input_data = (0,20,166.0,60.0,14.0,94.0,40.3)
np_data = np.asarray(input_data)
np_data_reshaped = np_data.reshape(1,-1)
prediction = rfr.predict(np_data_reshaped)
prediction

C:\Users\MONISALI\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([66.24])

PICKLE

In [97]:
import pickle
pickle.dump(rfr, open('rfr.pickle','wb'))

In [98]:
X_train.to_csv('X_train.csv')